version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:16.13.1. # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: npm run finaltest
workflows:
  version: 2
  build:
    jobs:
      - build