version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  nightly:
    triggers:
      - schedule:
          cron: '0 * * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run:
          name: Nightly Cypress E2E tests