version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  browser-tools: circleci/browser-tools@1
executors:
  with-chrome:
    docker:
      - image: 'cimg/node:13.12-browsers'
   
           
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:

          name: 4 machines
          requires:
            - cypress/install
           
          post-steps:
            - browser-tools/install-browser-tools
            - run: npm run testcases --record -- --parallel 
          parallelism: 3
          group: 3 machines
      - cypress/run:
          executor: with-chrome
          browser: chrome
          name: Chrome
          requires:
            - cypress/install