version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 
  cypress: cypress-io/cypress@1.1.0

executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'

jobs:
  build: 
    executor:
      name: win/default

    steps:
      - checkout
      - run: npm install
      - run: npm run testcases
              
executor: with-chrome
browser: chrome
record: true
parallel: true
parallelism: 2

    