version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
    steps:
      - checkout
      - run: npm ci
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - tmp
  combine_reports:
    working_directory: ~/tmp
    environment:
          TERM: xterm
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - attach_workspace:
          at: /tmp/mochawesome-report
      - run: ls /tmp/mochawesome-report
      - run: node ./lib/combine.js
      - store_artifacts:
          path: mochareports
  test1:
    working_directory: ~/tmp
    environment:
          TERM: xterm
    docker:
      - image: 'cypress/base:10'
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress tests 1
          command: npm run finaltest 
      - store_artifacts:
          path: mochawesome-report
      - persist_to_workspace:
          root: mochawesome-report
          paths:
            - test1.json
            - test1.html
  test2:
    working_directory: ~/tmp
    environment:
          TERM: xterm
    docker:
      - image: 'cypress/base:10'
      
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress tests 2
          command: npm run testcase1
      - store_artifacts:
          path: mochawesome-report
      - persist_to_workspace:
          root: mochawesome-report
          paths:
            - test2.json
            - test2.html   
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
     
      - combine_reports:
          requires:
            - test1
            - test2
            