
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  win: circleci/windows@2.2.0

  jobs:
    4x-electron: # name of your job
    executor:
      name: win/default # executor type
      size: "medium"
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'

workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:

          name: 4 machines
          requires:
            - cypress/install
          post-steps:
          
            - run: npm run --record --key 43946320-8aa1-470b-a125-6649b5b03cd6
            - run: npm run testcases
          parallelism: 4
          group: 4 machines
      - cypress/run:
          executor: with-chrome
          browser: chrome
          name: Chrome
          requires:
            - cypress/install