version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  win: circleci/windows@2.2.0

  jobs:
    platform: # name of your job
    executor:
      name: win/default # executor type
      size: "medium"
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: Chrome
          requires:
            - cypress/install
          executor: with-chrome
          browser: chrome
          post-steps:
            - run: npm run testcase2
      - cypress/run:
          name: Firefox
          requires:
            - cypress/install
          executor: cypress/browsers-chrome73-ff68
          start: npm start
          browser: firefox
          post-steps:
            - run: npm run testcase2
