version: 2.1
orbs:
  node: circleci/node@4.3.0
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  chrome:
    working_directory: /tmp
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - node/install-packages
      - run: 
          name: Running cypress tests to generate reports
          command: npm run testcase1 
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
     


workflows:
  end-to-end-tests:
    jobs:
      - chrome
    