version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  win: circleci/windows@2.2.0
  jobs:
    4x-electron: # name of your job

workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:

          name: 3 machines
          requires:
            - cypress/install
          post-steps:
            - run: npm run testcase2
          parallelism: 3
          group: 3 machines
      
      
    
      
        
            