
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: 4 machines
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 4
          group: 4 machines
      - cypress/run:
          name: Chrome
          requires:
            - cypress/install
          executor: with-chrome
          record: true
          parallel: true
          parallelism: 2
          browser: chrome
          spec: ./cypress/integration/testcases/*.js

    