version: 2.1
orbs:
  node: circleci/node@4.3.0
  browser-tools: circleci/browser-tools@1.1.3
  job-status-change: expo/job-status-change@1.0.11
  slack: circleci/slack@4.1

jobs:
  chrome:
    docker:
      - image: cimg/node:12.22-browsers
    


    steps:
      - checkout
      - browser-tools/install-chrome
      - node/install-packages
      - run:
          name: Run TestCafe tests on headless Chrome
          command: npm run testcase2 --browser chrome

  firefox:
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      - checkout
      - browser-tools/install-firefox
      - node/install-packages
      - run:
          name: Run tests on headless Firefox
          #https://support.circleci.com/hc/en-us/articles/360057590591-Ignoring-A-Failure-In-A-Step
          command: npm run testcase1 || true
      - run:
          name: Run commnads
          command: |
              echo "I will exit success status"
              exit 0
      - run:
          name: Run on fail status
          command: |
              echo "I am result of above failed job"
          when: on_fail
      - run:
          name: always Run
          command: |
              echo "I am result of above success/failed job"
          when: always
      - run:
          name: Run on success status
          command: |
              echo "I am result of above success job"
      - slack/notify:
          event: always
          "text": "*basic pass/fail*"


    status:
    description: |
      Tracks changes between the current and previous runs of the current job and writes the status change to an environment variable named CIRCLE_JOB_STATUS_CHANGE, with one of four values:

        success: the job was previously successful and is still successful
        failed:  the job previously failed and is still failing
        fixed:   the job previously failed but is now successful
        broke:   the job was previously successful but is now failing

  edge:
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Set up Microsoft Edge
          command: |
              curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
              sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
              sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
              sudo apt update
              sudo apt install microsoft-edge-beta
      - run:
          name: Run TestCafe tests on Microsoft Edge
          command: npm run testcase2 --browser edge

workflows:
  end-to-end-tests:
    jobs:
      - chrome
      - firefox 
      - hold:
          type: approval
          requires:
            - firefox
      - edge:
         requires:
            - hold

         
