version: 2.1
orbs:
  node: circleci/node@4.3.0
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'

      - browser-tools/install-chrome
      - save_cache:
          key: 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
          paths:
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - tmp
   
  chrome: 
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running cypress tests on browser chrome
          command: npm run testcase1
    
  firefox:
    working_directory: ~/tmp
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running cypress tests on browser firefox
          command: npm run testcase2
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - chrome:
          requires:
            - build
      - firefox:
          requires:
            - build
    
    
           