version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build-windows:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout
      - run: npm run testcase1
  build-macos:
    macos:
       xcode: 11.0.0
    steps:
      - checkout
      - run: npm run testcase1
  build-linux:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run: npm run testcase1
workflows:
  build-and-deploy:
    jobs:
    - build-windows
    - build-macos
    - build-linux 