version: 2
jobs:
  build:
    docker:
      - image: 'cypress/base:10'
    steps:
      - checkout
      - run: npm ci
  combine_reports:
    docker:
      - image: 'cypress/base:10'
    steps:
      - attach_workspace:
          at: cypress/reports
      - run: ls /tmp/mochawesome-report
  chrome:
    docker:
      - image: 'cypress/base:10'
    steps:
      - run:
          name: Running cypress tests 1
          command: >-
           npm run testcase1
     
      - store_artifacts:
          path: mochawesome-report
      - persist_to_workspace:
          root: mochawesome-report
          paths:
            - test1.json
            - test1.html
  firefox:
    docker:
      - image: 'cypress/base:10'
    steps:
      - run:
          name: Running cypress tests 2
          command: >-
            npm run testcase2
      - store_artifacts:
          path: cypress/reports
      - persist_to_workspace:
          root: cypress/reports
          paths:
            - test2.json
            - test2.html
  edge:
    docker:
      - image: 'cypress/base:10'
    steps:
      - run:
          name: Running cypress tests 3
          command: >-
            npm run testcase1
      - store_artifacts:
          path: cypress/reports
      - persist_to_workspace:
          root: cypress/reports
          paths:
            - test3.json
            - test3.html
    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - chrome:
          requires:
            - build
      - firefox:
          requires:
            - build
      - edge:
          requires:
            - build
  
      - combine_reports:
          requires:
            - chrome
            - firefox
            - edge