
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  win: circleci/windows@2.2.0

  jobs:
    4x-electron: # name of your job
    executor:
      name: win/default # executor type
      size: "medium"
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'

workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: default
          spec: './cypress/integration/testcases/testcase_01.spec.js'
          requires:
            - cypress/install
          
      - cypress/run:
          executor: win/default  
          browser: chrome
          name: Chrome
          spec: './cypress/integration/testcases/testcase_01.spec.js'
          requires:
            - cypress/install