version: 2.1

orbs:
  cypress: cypress-io/cypress@1.1.0

executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
  build:
    jobs:
      - cypress/run:
          executor: with-chrome
          browser: chrome
<<<<<<< HEAD
          record: true
          parallel: true
          parallelism: 2
=======
          
          
         

    
               
             
              
>>>>>>> 2b723c1d83c51ce9e0d16b59046a6af76b00a06b

    