version: 2.1
orbs:
  node: circleci/node@4.3.0
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  build:
     working_directory: ~/tmp
     docker:
      - image: cimg/node:12.22-browsers
     steps:
      - checkout
      - node/install-packages
      - run: npm ci
  combine_reports:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
    steps:
      - attach_workspace:
          at: cypress/reports
      - run: ls /tmp/mochawesome-report
  chrome:
    working_directory: ~/tmp
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      
      - browser-tools/install-chrome
      - run:
          name: Run tests on headless Chrome
          command: npm run testcase1
      - store_artifacts:
          path: mochawesome-report
      - persist_to_workspace:
          root: mochawesome-report
          paths:
            - test1.json
            - test1.html
  edge:
    working_directory: ~/tmp
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      - run:
          name: Set up Microsoft Edge
          command: |
              curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
              sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
              sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
              sudo apt update
              sudo apt install microsoft-edge-beta
      - run:
          name: Run tests on Microsoft Edge
          command: npm run testcase2
      - store_artifacts:
          path: cypress/reports
      - persist_to_workspace:
          root: cypress/reports
          paths:
            - test2.json
            - test2.html
  firefox:
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      - browser-tools/install-firefox
      - run:
          name: Run TestCafe tests on headless Firefox
          command: npm run testcase1 
      - store_artifacts:
          path: cypress/reports
      - persist_to_workspace:
          root: cypress/reports
          paths:
            - test3.json
            - test3.html
  
    
workflows:
  version: 2
  test_and_GenerateCombineReports:
    jobs:
      - build
      - chrome:
          requires:
            - build
      - edge:
          requires:
            - build
      - firefox:
          requires:
            - build

      - combine_reports:
          requires:
            - chrome
            - edge
            - firefox
            